version: '3.8'

services:
  autoscaler:
    image: eluki/swarm-service-autoscaler:latest
    environment:
      - AUTOSCALER_DNSNAME=tasks.autoscaler
      - AUTOSCALER_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      resources:
        limits:
          cpus: '1.0'
          memory: 100M
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "3"
