name: Autoscaller Build
on:
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: git fetch --prune --unshallow
    - name: Build And Push Swarm Service Autoscaler
      uses: docker/build-push-action@v1.1.0
      with:
        repository: eluki/swarm-service-autoscaler
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_with_ref: true
        #push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}
